name: library_scrape2
channels:
  - conda-forge
  - defaults
dependencies:
  - selenium
  - rise
  - python
  - ipython
  - ipykernel
  - nb_conda
  - nb_conda_kernels
  - jupyter_core
  - pytest
  - lxml
  - beautifulsoup4
  - pip:
    - delorean
